name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set the timestamp
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ env.TIMESTAMP }}

      # Push the image to Docker Hub
      - name: Push the Docker image
        run: docker push my-image-name:${{ env.TIMESTAMP }}
