name: Pytest API Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  Pytest-API-Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest tests/test_preprocessing.py -s
      - name: Archive Pytest test report
        uses: actions/upload-artifact@v4
        with:
          name: SuperTest-test-report
          path: report
      - name: Upload Pytest report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Pytest-test-report
          path: report